### ISSUE TITLE
omegaconf.errors.MissingMandatoryValue

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [zqh0253/3DitScene#13]
Hi! Nice work!
I meet a problem:

Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/3DitScene/launch.py", line 301, in <module>
    main(args, extras)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/mnt/cloud_disk/yyhyyh/3DitScene/custom/threestudio-3dgs/system/scene_lang.py", line 63, in configure
    super().configure()
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/systems/base.py", line 292, in configure
    self.geometry = threestudio.find(self.cfg.geometry_type)(self.cfg.geometry)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/utils/base.py", line 100, in __init__
    self.cfg = parse_structured(self.Config, cfg)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/utils/config.py", line 127, in parse_structured
    scfg = OmegaConf.structured(fields(**cfg))
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/dictconfig.py", line 451, in _get_impl
    return self._resolve_with_default(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/omegaconf/basecontainer.py", line 96, in _resolve_with_default
    raise MissingMandatoryValue("Missing mandatory value: $FULL_KEY")
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: geometry.prompt
    full_key: geometry.prompt
    object_type=dict
bash: system.geometry.geometry_convert_from=depth:assets/teddy.png: No such file or directory
system.prompt_processor.prompt=a teddy bear in Times Square: command not found

I cant solve it now.Please help me.Thank you!

**Comment by yyhyyhyyhyyh** [comment]
I mistake the space for the enter

**Comment by murmurelo111** [comment]
hello! I met the same problem, could you tell me how to solve it?

**Comment by yyhyyhyyhyyh** [comment]
hello. If you copy the command directly, the space may become a return. You can check it
