### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [zqh0253/3DitScene#14]
Hi!I want to ask about the error:

Traceback (most recent call last):
  File "/mnt/cloud_disk/yyhyyh/3DitScene/launch.py", line 301, in <module>
    main(args, extras)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/launch.py", line 169, in main
    system: BaseSystem = threestudio.find(cfg.system_type)(
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/systems/base.py", line 51, in __init__
    self.configure()
  File "/mnt/cloud_disk/yyhyyh/3DitScene/custom/threestudio-3dgs/system/scene_lang.py", line 63, in configure
    super().configure()
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/systems/base.py", line 292, in configure
    self.geometry = threestudio.find(self.cfg.geometry_type)(self.cfg.geometry)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/threestudio/utils/base.py", line 102, in __init__
    self.configure(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/3DitScene/custom/threestudio-3dgs/geometry/gaussian_base.py", line 586, in configure
    self.base_inpainting_pipe = StableDiffusionInpaintPipeline.from_pretrained("runwayml/stable-diffusion-inpainting", torch_dtype=torch.float16)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1096, in from_pretrained
    cached_folder = cls.download(
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/mnt/cloud_disk/yyhyyh/anaconda3/envs/3DS/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 1905, in download
    raise EnvironmentError(
OSError: Cannot load model runwayml/stable-diffusion-inpainting: model is not cached locally and an error occured while trying to fetch metadata from the Hub. Please check out the root cause in the stacktrace above.

### But what I really want to ask is that I can no longer find this model(**runwayml/stable-diffusion-inpainting**) on the Huggingface,Can this model still be used, or is it set with permissions.
Thank you!

**Comment by zqh0253** [comment]
Hi, runwayml has removed the model on huggingface. You can try to use other inpainting model like https://huggingface.co/stabilityai/stable-diffusion-2-inpainting.

**Comment by yyhyyhyyhyyh** [comment]
ok.it works
