### ISSUE TITLE
No Optimizer Config

### ISSUE THREAD

**Issue by quangtannguyen** [zqh0253/3DitScene#9]
Hi, congratulation on your great work. While running your code, I encountered the following issue:
`Traceback (most recent call last):
  File "/mnt/disks/datadriver/work_tan/3DitScene/launch.py", line 301, in <module>
    main(args, extras)
  File "/mnt/disks/datadriver/work_tan/3DitScene/launch.py", line 244, in main
    trainer.fit(system, datamodule=dm, ckpt_path=cfg.resume)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 963, in _run
    self.strategy.setup(self)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 159, in setup
    self.setup_optimizers(trainer)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 139, in setup_optimizers
    self.optimizers, self.lr_scheduler_configs = _init_optimizers_and_lr_schedulers(self.lightning_module)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 186, in _init_optimizers_and_lr_schedulers
    optimizers, lr_schedulers, monitor = _configure_optimizers(optim_conf)
  File "/mnt/disks/datadriver/miniconda3/envs/3dit-scene/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 237, in _configure_optimizers
    raise MisconfigurationException(
lightning_fabric.utilities.exceptions.MisconfigurationException: Unknown configuration for model optimizers. Output from `model.configure_optimizers()` should be one of:
 * `Optimizer`
 * [`Optimizer`]
 * ([`Optimizer`], [`LRScheduler`])
 * {"optimizer": `Optimizer`, (optional) "lr_scheduler": `LRScheduler`}`

Look like you did not define the optimizer. Could you please help me solving it? Thank you for your attention to this matter.

**Comment by quangtannguyen** [comment]
For `lightning` is `2.0.0` and `pytorch-lightning` is `2.2.5`

**Comment by zqh0253** [comment]
>  Look like you did not define the optimizer.

This is not ture. The optimizer is defined at [here](https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/custom/threestudio-3dgs/system/scene_lang.py#L85). Can you set a breakpoint here to check the return value?

**Comment by quangtannguyen** [comment]
Hi, turn out it was my fault. I did not set the path to my tested picture for the geometry.geometry_convert_from in the config file so the geometry.optimizer is None. Really appreciate for your help.

**Comment by quangtannguyen** [comment]
May I ask what is the meaning of these variables `c2w3x4` and `c2w` from this [line](https://github.com/zqh0253/3DitScene/blob/d9c4592cbca692d939ef635b36b46e603ff3500f/threestudio/data/uncond.py#L425). Thank you.

**Comment by zqh0253** [comment]
Hi, c2w means the transformation matrix from the camera coordinate to the world coordinate.

**Comment by quangtannguyen** [comment]
Hi, now I'm really curious to know how we could zoom in or zoom out the camera. Could you please suggest me some possible ways to do this? Thank you.

**Comment by zqh0253** [comment]
You can move the camera position along the line connecting the camera and the target center:
```
lookat = F.normalize(self.center - old_camera_positions, dim=-1)
camera_positions = old_camera_positions + alpha * lookat
```

In this context, setting alpha to a value less than 0 will zoom out, while setting alpha to a value greater than 0 will zoom in.

**Comment by quangtannguyen** [comment]
Thank you very much. You're so kind replying all of my questions. Really appreciate it!

**Comment by zqh0253** [comment]
> Thank you very much. You're so kind replying all of my questions. Really appreciate it!

You're more than welcome :)
